### ISSUE TITLE
Game is trash

### ISSUE THREAD

**Issue by JashonBrown** [jakedorne/Dank-Game#1]
Hey, can you fix the issue listed in the title pls, thx

**Comment by jakedorne** [comment]
working on a fix for this next patch

**Comment by JashonBrown** [comment]
So hyped for next patch!!

**Comment by LaurynDorne** [comment]
Why am I in this send help

**Comment by JashonBrown** [comment]
You were probably so hyped for this game that you followed it. Did you see the patch notes for next patch? They are fixing that massive bug where the game was bad!!
